name: Build job

on:
  # Every working days at 16:00 UTC
  schedule:
    - cron: '0 16 * * 1-5'
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        type: boolean
        description: Creates a draft release
        required: false

jobs:
  build-app:
    runs-on: windows-latest
    
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'codescapes-io/codescapes'
          fetch-depth: 0
          token: ${{ secrets.PA_TOKEN }}
        if: github.event.inputs.git-ref == ''
        
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'codescapes-io/codescapes'
          fetch-depth: 0
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ref: ${{ github.event.inputs.git-ref }}
          
      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1
          
      - name: Prepare build
        shell: bash
        run: |
          set -e
          
          curl https://raw.githubusercontent.com/codescapes-io/codescapes-nightly/master/electron-builder.json -o packages/cs-electron/electron-builder.json
          
          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV
          
          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^r//")
          commit_count_diff=$(expr $commit_count - $prev_commit_count)
          prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)
          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV
          
          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.PA_TOKEN }}" \
            "https://api.github.com/repos/codescapes-io/codescapes/compare/$prev_release_sha...$current_sha" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_ENV
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install deps
        run: yarn install --network-timeout 1000000

      - name: Build/release Electron app
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.PA_TOKEN }}
          CHANNEL: preview
          CI_PIPELINE_IID: ${{ env.COMMIT_COUNT }}
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          name: Codescapes Preview r${{ env.COMMIT_COUNT }}
          body: |
            ### Commits
            
            https://github.com/codescapes-io/codescapes/compare/${{ env.PREV_RELEASE_SHA }}...${{ env.CURRENT_SHA }}
            
            ${{ env.COMMIT_LOGS }}
          
          files: |
            packages/cs-electron/dist/*.exe
            packages/cs-electron/dist/*.exe.*
            packages/cs-electron/dist/latest.yml
            
          draft: ${{ github.event.inputs.dry-run }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 28
          delete_tags: true
