name: Build job

on:
  # Every Saturday at 21:00 UTC
  schedule:
    - cron: '0 23 * * 0'
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        type: boolean
        description: Creates a draft release
        required: false

jobs:
  build-app:
    runs-on: windows-latest
    
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'codescapes-io/codescapes'
          fetch-depth: 0
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
        if: github.event.inputs.git-ref == ''
        
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'codescapes-io/codescapes'
          fetch-depth: 0
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ref: ${{ github.event.inputs.git-ref }}
          
      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1
          
      - name: Prepare build
        shell: bash
        run: |
          set -e
          
          curl https://raw.githubusercontent.com/codescapes-io/codescapes-nightly/master/electron-builder.json -o packages/cs-electron/electron-builder.json
          
          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV
