name: Build job

on:
  # Every Saturday at 21:00 UTC
  schedule:
    - cron: '0 23 * * 0'
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        type: boolean
        description: Creates a draft release
        required: false

jobs:
  build-app:
    runs-on: windows-latest
    
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'codescapes-io/codescapes'
          fetch-depth: 0
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
        if: github.event.inputs.git-ref == ''
        
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'codescapes-io/codescapes'
          fetch-depth: 0
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ref: ${{ github.event.inputs.git-ref }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install deps
        run: lerna bootstrap
        
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          package_root: ./packages/cs-electron/

      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 28
          delete_tags: true
